backend:
  name: github
  repo: parikramaka/parikramaka-site  # your GitHub org/repo
  branch: main
  auth_scope: repo
  open_authoring: true

media_folder: "static/images/uploads"
public_folder: "/static/images/uploads"

publish_mode: editorial_workflow

site_url: "https://parikramaka.github.io/parikramaka-site"

collections:

  - name: "archive"
    label: "Archive"
    folder: "content/archive"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Status", name: "status", widget: "select", options: ["success", "failure"] }
      - { label: "Subsystems", name: "subsystems", widget: "list" }
      - { label: "Personas", name: "personas", widget: "list" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Lessons Learned", name: "lessons_learned", widget: "text" }
      - { label: "Media", name: "media", widget: "list", fields: [
          { label: "Type", name: "type", widget: "select", options: ["image", "video", "diagram"] },
          { label: "URL", name: "url", widget: "string" }
        ]}
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "mechanical"
    label: "Subsystem - Mechanical"
    folder: "content/subsystems/mechanical"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Cover Image", name: "cover_image", widget: "image" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "personas"
    label: "Personas"
    folder: "content/personas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "GitHub", name: "github", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }

  - name: "resources"
    label: "Resources"
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["dataset", "software", "reference"] }
      - { label: "Body", name: "body", widget: "markdown" }
